GET http://localhost/api/resource

###
POST http://localhost/api/resource

###
PUT http://localhost/api/resource/4

###
PATCH http://localhost/api/resource/1

###
DELETE http://localhost/api/resource/2
